CREATE TABLE MCHTI.ADM_PARAM
(
  ID               NUMBER(19,2)                 NOT NULL,
  VERSION          NUMBER(10),
  ADM_WIDGET_TYPE  VARCHAR2(30 CHAR)            NOT NULL,
  CMD              VARCHAR2(255 CHAR),
  DEFAULT_VAL      VARCHAR2(255 CHAR),
  HELP_TEXT        VARCHAR2(255 CHAR),
  IS_ACTIVE        NUMBER(1),
  IS_MANDATORY     NUMBER(1),
  PARAM_NAME       VARCHAR2(30 CHAR)            NOT NULL,
  SL_NO            NUMBER(10),
  TITLE            VARCHAR2(30 CHAR)            NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ADM_PROCESS
(
  ID         NUMBER(19,2)                       NOT NULL,
  VERSION    NUMBER(10),
  CMD        VARCHAR2(2000 CHAR)                NOT NULL,
  CODE       VARCHAR2(6 CHAR)                   NOT NULL,
  IS_ACTIVE  NUMBER(1),
  REMARKS    VARCHAR2(500 CHAR),
  SL_NO      NUMBER(10),
  TITLE      VARCHAR2(50 CHAR)                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ADM_PROCESS_DETAIL
(
  ID              NUMBER(19,2)                  NOT NULL,
  VERSION         NUMBER(10),
  ADM_ZONE_TYPE   VARCHAR2(30 CHAR)             NOT NULL,
  SL_NO           NUMBER(10),
  ADM_PARAM_ID    NUMBER(19,2)                  NOT NULL,
  ADM_PROCESS_ID  NUMBER(19,2)                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ADM_REPORT
(
  ID         NUMBER(19,2)                       NOT NULL,
  VERSION    NUMBER(10),
  CODE       VARCHAR2(4 CHAR)                   NOT NULL,
  FILE_NAME  VARCHAR2(30 CHAR)                  NOT NULL,
  IS_ACTIVE  NUMBER(1),
  REMARKS    VARCHAR2(500 CHAR),
  SL_NO      NUMBER(10),
  TITLE      VARCHAR2(50 CHAR)                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ADM_REPORT_DETAIL
(
  ID             NUMBER(19,2)                   NOT NULL,
  VERSION        NUMBER(10),
  SL_NO          NUMBER(10),
  ADM_PARAM_ID   NUMBER(19,2)                   NOT NULL,
  ADM_REPORT_ID  NUMBER(19,2)                   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.AUTH_MENU
(
  ID                  NUMBER(19,2)              NOT NULL,
  VERSION             NUMBER(10),
  DESCRIPTION         VARCHAR2(100 CHAR),
  DISPLAY_ICON_CLASS  VARCHAR2(128 CHAR),
  DISPLAY_NAME        VARCHAR2(30 CHAR)         NOT NULL,
  IS_ACTIVE           NUMBER(1),
  IS_EXTERNAL         NUMBER(1),
  IS_OPEN_NEW_TAB     NUMBER(1),
  MENU_TYPE           VARCHAR2(100 CHAR),
  SL_NO               NUMBER(10),
  TOOLTIP             VARCHAR2(30 CHAR),
  URL_PATH            VARCHAR2(255 CHAR)        NOT NULL,
  PARENT_ID           NUMBER(19,2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.AUTH_QUESTION
(
  ID        NUMBER(19,2)                        NOT NULL,
  QUESTION  VARCHAR2(255 CHAR),
  VERSION   NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.AUTH_REQUEST_MAP
(
  ID                NUMBER(19,2)                NOT NULL,
  CONFIG_ATTRIBUTE  VARCHAR2(255 CHAR),
  HTTP_METHOD       NUMBER(10),
  URL               VARCHAR2(255 CHAR),
  VERSION           NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.AUTH_ROLE
(
  ID         NUMBER(19,2)                       NOT NULL,
  AUTHORITY  VARCHAR2(255 CHAR),
  VERSION    NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.AUTH_TOKEN
(
  SERIES     VARCHAR2(255 CHAR)                 NOT NULL,
  LAST_USED  TIMESTAMP(6),
  TOKEN      VARCHAR2(255 CHAR)                 NOT NULL,
  USERNAME   VARCHAR2(255 CHAR)                 NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.AUTH_USER
(
  ID                       NUMBER(19,2)         NOT NULL,
  ACCOUNT_NON_EXPIRED      NUMBER(1)            NOT NULL,
  ACCOUNT_NON_LOCKED       NUMBER(1)            NOT NULL,
  CREDENTIALS_NON_EXPIRED  NUMBER(1)            NOT NULL,
  DISPLAY_NAME             VARCHAR2(9 CHAR)     NOT NULL,
  DOB                      DATE,
  DOJ                      DATE,
  EMAIL                    VARCHAR2(30 CHAR),
  ENABLED                  NUMBER(1)            NOT NULL,
  FULL_NAME                VARCHAR2(50 CHAR)    NOT NULL,
  GENDER                   VARCHAR2(6 CHAR),
  PASSWORD                 VARCHAR2(255 CHAR)   NOT NULL,
  PIC_FILE                 VARCHAR2(255 CHAR),
  USERNAME                 VARCHAR2(255 CHAR)   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.AUTH_USER_AUTH_QUESTION
(
  ANSWER            VARCHAR2(30 CHAR)           NOT NULL,
  AUTH_USER_ID      NUMBER(19,2)                NOT NULL,
  AUTH_QUESTION_ID  NUMBER(19,2)                NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.AUTH_USER_AUTH_ROLE
(
  AUTH_USER_ID  NUMBER(19,2)                    NOT NULL,
  AUTH_ROLE_ID  NUMBER(19,2)                    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.CLIENT
(
  ID         NUMBER(19,2)                       NOT NULL,
  VERSION    NUMBER(10),
  CITY       VARCHAR2(30 CHAR),
  LINE_ONE   VARCHAR2(50 CHAR)                  NOT NULL,
  LINE_TWO   VARCHAR2(50 CHAR)                  NOT NULL,
  STREET     VARCHAR2(30 CHAR),
  ZIP        VARCHAR2(10 CHAR),
  CODE       VARCHAR2(20 CHAR)                  NOT NULL,
  DOB        DATE,
  EMAIL      VARCHAR2(30 CHAR),
  FULL_NAME  VARCHAR2(100 CHAR)                 NOT NULL,
  GENDER     VARCHAR2(6 CHAR),
  PIC_FILE   VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.CLIENT_COMPANY
(
  ID                NUMBER(19,2)                NOT NULL,
  VERSION           NUMBER(10),
  CITY              VARCHAR2(30 CHAR),
  LINE_ONE          VARCHAR2(50 CHAR)           NOT NULL,
  LINE_TWO          VARCHAR2(50 CHAR)           NOT NULL,
  STREET            VARCHAR2(30 CHAR),
  ZIP               VARCHAR2(10 CHAR),
  CODE              VARCHAR2(20 CHAR)           NOT NULL,
  COMPANY_TYPE      VARCHAR2(30 CHAR),
  EMAIL             VARCHAR2(30 CHAR),
  FULL_NAME         VARCHAR2(100 CHAR)          NOT NULL,
  ORIENTATION_DATE  DATE,
  PIC_FILE          VARCHAR2(255 CHAR),
  REG_NO            VARCHAR2(30 CHAR),
  WEB               VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.COMPANY
(
  ID                NUMBER(19,2)                NOT NULL,
  VERSION           NUMBER(10),
  CITY              VARCHAR2(30 CHAR),
  LINE_ONE          VARCHAR2(50 CHAR)           NOT NULL,
  LINE_TWO          VARCHAR2(50 CHAR)           NOT NULL,
  STREET            VARCHAR2(30 CHAR),
  ZIP               VARCHAR2(10 CHAR),
  CODE              VARCHAR2(20 CHAR)           NOT NULL,
  COMPANY_TYPE      VARCHAR2(30 CHAR),
  EMAIL             VARCHAR2(30 CHAR),
  FULL_NAME         VARCHAR2(100 CHAR)          NOT NULL,
  ORIENTATION_DATE  DATE,
  PIC_FILE          VARCHAR2(255 CHAR),
  REG_NO            VARCHAR2(30 CHAR),
  WEB               VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.CUSTOMIZED_HOLIDAY_APP
(
  ID            NUMBER(19,2)                    NOT NULL,
  VERSION       NUMBER(10),
  APP_DATE      DATE,
  CODE          VARCHAR2(20 CHAR)               NOT NULL,
  END_DATE      DATE,
  HOLIDAY_TYPE  VARCHAR2(30 CHAR)               NOT NULL,
  REMARKS       VARCHAR2(500 CHAR),
  START_DATE    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.DEPARTMENT
(
  ID         NUMBER(19,2)                       NOT NULL,
  VERSION    NUMBER(10),
  CODE       VARCHAR2(20 CHAR)                  NOT NULL,
  IS_ACTIVE  NUMBER(1),
  REMARKS    VARCHAR2(500 CHAR),
  SLNO       NUMBER(10),
  TITLE      VARCHAR2(100 CHAR)                 NOT NULL,
  TITLE_BNG  VARCHAR2(200 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.DESIGNATION
(
  ID         NUMBER(19,2)                       NOT NULL,
  CODE       VARCHAR2(20 CHAR)                  NOT NULL,
  IS_ACTIVE  NUMBER(1),
  REMARKS    VARCHAR2(500 CHAR),
  SLNO       NUMBER(10),
  TITLE      VARCHAR2(100 CHAR)                 NOT NULL,
  TITLE_BNG  VARCHAR2(200 CHAR),
  VERSION    NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.EMPLOYEE
(
  ID         NUMBER(19,2)                       NOT NULL,
  VERSION    NUMBER(10),
  CITY       VARCHAR2(30 CHAR),
  LINE_ONE   VARCHAR2(50 CHAR),
  LINE_TWO   VARCHAR2(50 CHAR),
  STREET     VARCHAR2(30 CHAR),
  ZIP        VARCHAR2(10 CHAR),
  DOB        DATE,
  EMAIL      VARCHAR2(30 CHAR),
  FULL_NAME  VARCHAR2(100 CHAR)                 NOT NULL,
  GENDER     VARCHAR2(6 CHAR),
  PIC_FILE   VARCHAR2(255 CHAR),
  CODE       VARCHAR2(20 CHAR)                  NOT NULL,
  DOJ        DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.GENERAL_HOLIDAY
(
  ID            NUMBER(19,2)                    NOT NULL,
  CODE          VARCHAR2(20 CHAR)               NOT NULL,
  IS_ACTIVE     NUMBER(1),
  REMARKS       VARCHAR2(500 CHAR),
  TITLE         VARCHAR2(100 CHAR)              NOT NULL,
  VERSION       NUMBER(10),
  ON_DAY        NUMBER(10)                      NOT NULL,
  ON_MONTH      NUMBER(10)                      NOT NULL,
  HOLIDAY_TYPE  VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.HIBERNATE_SEQUENCES
(
  SEQUENCE_NAME  VARCHAR2(255 CHAR)             NOT NULL,
  NEXT_VAL       NUMBER(19)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ABSTRACT_AUDITABLE_ENTITY
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ABSTRACT_ENTITY
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ADM_PARAM
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ADM_PROCESS
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ADM_PROCESS_DETAIL
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ADM_REPORT
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ADM_REPORT_DETAIL
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_AUTH_MENU
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_AUTH_QUESTION
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_AUTH_REQUEST_MAP
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_AUTH_ROLE
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_CLIENT
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_CLIENT_COMPANY
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_COMPANY
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_CUSTOMIZED_HOLIDAY_APP
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_EMPLOYEE
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_GENERAL_HOLIDAY
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_MANUAL_ATTN_DAILY
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_PERSON
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_SUPPLIER
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_SUPPLIER_COMPANY
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_TRANSACSION
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ZX_ANY_OBJECT
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ZX_DEPT
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ZX_DESG
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ZX_EMP
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE GLOBAL TEMPORARY TABLE MCHTI.HT_ZX_EMP_EDU_DTL
(
  ID  NUMBER(19,2)                              NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE TABLE MCHTI.LEAVE_APP
(
  ID                    NUMBER(19,2)            NOT NULL,
  ADDRESS_DURING_LEAVE  VARCHAR2(500 CHAR),
  APP_DATE              DATE,
  CODE                  VARCHAR2(20 CHAR)       NOT NULL,
  CONTACT_NO            VARCHAR2(500 CHAR),
  END_DATE              DATE,
  LEAVE_TYPE            VARCHAR2(30 CHAR)       NOT NULL,
  REASON_FOR_LEAVE      VARCHAR2(500 CHAR),
  START_DATE            DATE,
  VERSION               NUMBER(10),
  EMPLOYEE_ID           NUMBER(19,2)            NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.LOOKUP
(
  ID         NUMBER(19,2)                       NOT NULL,
  CODE       VARCHAR2(20 CHAR)                  NOT NULL,
  IS_ACTIVE  NUMBER(1),
  KEYWORD    VARCHAR2(30 CHAR),
  REMARKS    VARCHAR2(500 CHAR),
  SL_NO      NUMBER(10),
  TITLE      VARCHAR2(100 CHAR)                 NOT NULL,
  TITLE_BNG  VARCHAR2(500 CHAR),
  VERSION    NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.MANUAL_ATTN_DAILY
(
  ID           NUMBER(19,2)                     NOT NULL,
  VERSION      NUMBER(10),
  EDIT_DATE    DATE,
  ENTRY_DATE   DATE                             NOT NULL,
  EDIT_BY_ID   NUMBER(19,2),
  ENTRY_BY_ID  NUMBER(19,2)                     NOT NULL,
  ATTN_DATE    DATE                             NOT NULL,
  IN_TIME      VARCHAR2(5 CHAR),
  OUT_TIME     VARCHAR2(5 CHAR),
  REMARKS      VARCHAR2(500 CHAR),
  EMPLOYEE_ID  NUMBER(19,2)                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.PERIOD
(
  ID           NUMBER(19,2)                     NOT NULL,
  CODE         VARCHAR2(20 CHAR)                NOT NULL,
  END_DATE     DATE,
  START_DATE   DATE,
  TITLE        VARCHAR2(100 CHAR)               NOT NULL,
  VERSION      NUMBER(10),
  PERIOD_TYPE  VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.PERSISTENT_LOGINS
(
  SERIES     VARCHAR2(255 CHAR)                 NOT NULL,
  LAST_USED  TIMESTAMP(6),
  TOKEN      VARCHAR2(255 CHAR)                 NOT NULL,
  USERNAME   VARCHAR2(30 CHAR)                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.PROC_OUT_ATTN_DAILY
(
  ATTN_MODE         VARCHAR2(5 CHAR)            NOT NULL,
  REMARKS           VARCHAR2(500 CHAR),
  EMPLOYEE_ID       NUMBER(19,2)                NOT NULL,
  TRANSACTION_TIME  DATE                        NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.PROC_OUT_ATTN_PERIOD
(
  ID                     NUMBER(19,2)           NOT NULL,
  ATTN_STS               NUMBER(10)             NOT NULL,
  DAY_ABSENT             NUMBER(10),
  DAY_CL                 NUMBER(10),
  DAY_EARLY_OUT          NUMBER(10),
  DAY_EL                 NUMBER(10),
  DAY_HOLIDAY            NUMBER(10),
  DAY_HOLIDAY_WORK       NUMBER(10),
  DAY_LATE               NUMBER(10),
  DAY_LATE_IN_EARLY_OUT  NUMBER(10),
  DAY_LWP                NUMBER(10),
  DAY_ML                 NUMBER(10),
  DAY_PRESENT            NUMBER(10),
  DAY_SL                 NUMBER(10),
  GEN_TYPE               NUMBER(10)             NOT NULL,
  OT_HOUR_EXTRA          FLOAT(126),
  OT_HOUR_HOLIDAY        FLOAT(126),
  OT_HOUR_NORMAL         FLOAT(126),
  OT_HOUR_SRO            FLOAT(126),
  EMPLOYEE_ID            NUMBER(19,2)           NOT NULL,
  PERIOD_ID              NUMBER(19,2)           NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.PROC_OUT_CALENDER
(
  CAL_DATE       DATE,
  IS_APPLICABLE  NUMBER(1),
  REMARKS        VARCHAR2(500 CHAR),
  HOLIDAY_TYPE   VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ROSTER
(
  ID         NUMBER(19,2)                       NOT NULL,
  CODE       VARCHAR2(20 CHAR)                  NOT NULL,
  FORMULA    VARCHAR2(500 CHAR),
  IS_ACTIVE  NUMBER(1),
  REMARKS    VARCHAR2(500 CHAR),
  SL_NO      NUMBER(10),
  TITLE      VARCHAR2(100 CHAR)                 NOT NULL,
  VERSION    NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.SHIFT
(
  ID               NUMBER(19,2)                 NOT NULL,
  CODE             VARCHAR2(20 CHAR)            NOT NULL,
  END_BUF_MIN      NUMBER(10),
  END_HR           NUMBER(10)                   NOT NULL,
  END_MIN          NUMBER(10),
  IS_ACTIVE        NUMBER(1),
  ORIENTATION_MIN  NUMBER(10),
  REMARKS          VARCHAR2(500 CHAR),
  SHIFT_TYPE       VARCHAR2(30 CHAR),
  SL_NO            NUMBER(10),
  START_BUF_MIN    NUMBER(10),
  START_HR         NUMBER(10)                   NOT NULL,
  START_MIN        NUMBER(10),
  TITLE            VARCHAR2(100 CHAR)           NOT NULL,
  TITLE_BNG        VARCHAR2(500 CHAR),
  VERSION          NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.SUPPLIER
(
  ID         NUMBER(19,2)                       NOT NULL,
  VERSION    NUMBER(10),
  CITY       VARCHAR2(30 CHAR),
  LINE_ONE   VARCHAR2(50 CHAR)                  NOT NULL,
  LINE_TWO   VARCHAR2(50 CHAR)                  NOT NULL,
  STREET     VARCHAR2(30 CHAR),
  ZIP        VARCHAR2(10 CHAR),
  CODE       VARCHAR2(20 CHAR)                  NOT NULL,
  DOB        DATE,
  EMAIL      VARCHAR2(30 CHAR),
  FULL_NAME  VARCHAR2(100 CHAR)                 NOT NULL,
  GENDER     VARCHAR2(6 CHAR),
  PIC_FILE   VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.SUPPLIER_COMPANY
(
  ID                NUMBER(19,2)                NOT NULL,
  VERSION           NUMBER(10),
  CITY              VARCHAR2(30 CHAR),
  LINE_ONE          VARCHAR2(50 CHAR)           NOT NULL,
  LINE_TWO          VARCHAR2(50 CHAR)           NOT NULL,
  STREET            VARCHAR2(30 CHAR),
  ZIP               VARCHAR2(10 CHAR),
  CODE              VARCHAR2(20 CHAR)           NOT NULL,
  COMPANY_TYPE      VARCHAR2(30 CHAR),
  EMAIL             VARCHAR2(30 CHAR),
  FULL_NAME         VARCHAR2(100 CHAR)          NOT NULL,
  ORIENTATION_DATE  DATE,
  PIC_FILE          VARCHAR2(255 CHAR),
  REG_NO            VARCHAR2(30 CHAR),
  WEB               VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.TRANSACSION
(
  ID          NUMBER(19,2)                      NOT NULL,
  VERSION     NUMBER(10),
  AMOUNT      FLOAT(126),
  REMARKS     VARCHAR2(30 CHAR),
  TRANS_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ZX_ANY_OBJECT
(
  ID          NUMBER(19,2)                      NOT NULL,
  CODE        VARCHAR2(20 CHAR)                 NOT NULL,
  IS_ACTIVE   NUMBER(1),
  REMARKS     VARCHAR2(500 CHAR),
  SL_NO       NUMBER(10),
  START_DATE  DATE,
  TITLE       VARCHAR2(100 CHAR)                NOT NULL,
  VERSION     NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ZX_DEPT
(
  ID         NUMBER(19,2)                       NOT NULL,
  VERSION    NUMBER(10),
  CODE       VARCHAR2(20 CHAR)                  NOT NULL,
  IS_ACTIVE  NUMBER(1),
  REMARKS    VARCHAR2(500 CHAR),
  SL_NO      NUMBER(10),
  TITLE      VARCHAR2(100 CHAR)                 NOT NULL,
  TITLE_BNG  VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ZX_DESG
(
  ID         NUMBER(19,2)                       NOT NULL,
  VERSION    NUMBER(10),
  CODE       VARCHAR2(20 CHAR)                  NOT NULL,
  IS_ACTIVE  NUMBER(1),
  REMARKS    VARCHAR2(500 CHAR),
  SL_NO      NUMBER(10),
  TITLE      VARCHAR2(100 CHAR)                 NOT NULL,
  TITLE_BNG  VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ZX_LOOKUP
(
  ID                 NUMBER(19,2)               NOT NULL,
  CODE               VARCHAR2(20 CHAR)          NOT NULL,
  IS_ACTIVE          NUMBER(1),
  REMARKS            VARCHAR2(500 CHAR),
  SL_NO              NUMBER(10),
  TITLE              VARCHAR2(100 CHAR)         NOT NULL,
  TITLE_BNG          VARCHAR2(500 CHAR),
  ZX_LOOKUP_KEYWORD  VARCHAR2(30 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MCHTI.UK_CMNA8LOP8AFHFSI0V0IJSU8SH ON MCHTI.SUPPLIER_COMPANY
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007728.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007726.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_L66VGY7V2SNPH53MAF8ERN37 ON MCHTI.SUPPLIER
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007716.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_QTHLGMLLTHWG18UIYQBS0KXWR ON MCHTI.SHIFT
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007705.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_N57PIT3MF92OK6IXIG8CIS7AW ON MCHTI.ROSTER
(CODE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.PROC_OUT_CALENDER_PK ON MCHTI.PROC_OUT_CALENDER
(CAL_DATE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007702.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.PROC_OUT_ATTN_DAILY_PK ON MCHTI.PROC_OUT_ATTN_DAILY
(EMPLOYEE_ID, TRANSACTION_TIME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.UK_A6C251UOVNX2CP2C3VV2DENTK ON MCHTI.PERSISTENT_LOGINS
(USERNAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.UK_3GQ9WKITBP2AVE684IU50MHN7 ON MCHTI.PERSISTENT_LOGINS
(TOKEN)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007967.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007698.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UKS4EH3QILLPF7CORNN721I63V3 ON MCHTI.MANUAL_ATTN_DAILY
(EMPLOYEE_ID, ATTN_DATE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C008047.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007690.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UKOXOGAD86STS9G9SRTXXTK1PNK ON MCHTI.LOOKUP
(KEYWORD, TITLE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007689.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007684.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007681.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_72HK7RAQTDNIPYOKI9UXJNFD5 ON MCHTI.GENERAL_HOLIDAY
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007670.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_T7BM2WG7CURAQJ764MM8ORUG8 ON MCHTI.EMPLOYEE
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007668.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_IJV6ABSH47WCHE44QUAFC5VE7 ON MCHTI.DESIGNATION
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007666.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_RH6EQ4TT0PG176FYHR58S6UXL ON MCHTI.DEPARTMENT
(CODE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.UK_E7J4JO8JQWDXKAHR112WANQ40 ON MCHTI.CUSTOMIZED_HOLIDAY_APP
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007963.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007662.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_NIHSPJAA28E7UCECVP68H4AMH ON MCHTI.COMPANY
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007660.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_4SR4K1U0SXXQQ1JMBHL8JBX1T ON MCHTI.CLIENT_COMPANY
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007658.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_RB1NWD8YAH66CM1JQN55F5DRG ON MCHTI.CLIENT
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007657.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007656.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007654.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.AUTH_USER_U01 ON MCHTI.AUTH_USER
(USERNAME)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007651.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_CN1M62UD9S70X2DUN44QKOD2P ON MCHTI.AUTH_TOKEN
(TOKEN)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.UK_FU8V8E6E6POK9SFW2VAA0WQBX ON MCHTI.AUTH_TOKEN
(USERNAME)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007649.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_SL3AD8KJNF8EBO7BERRSU1HO ON MCHTI.AUTH_ROLE
(AUTHORITY)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007648.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007647.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_RWUG86W16X8XH21XS8JK22JGB ON MCHTI.AUTH_MENU
(URL_PATH)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007959.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UKNQJ85REHRPQ7KHVQL95UJHB19 ON MCHTI.ADM_REPORT_DETAIL
(ADM_REPORT_ID, ADM_PARAM_ID)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007955.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_PBMRPPRR68RUIABL2AWCK3VLB ON MCHTI.ADM_REPORT
(FILE_NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.UK_12A5A4GXF9JCHJ7DLMNW9BQ3O ON MCHTI.ADM_REPORT
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007951.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UKCGERTCYSXNCWEA6DPQNEDVPEA ON MCHTI.ADM_PROCESS_DETAIL
(ADM_PROCESS_ID, ADM_PARAM_ID, ADM_ZONE_TYPE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007946.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_ER7CCFDE575KLECL9LSKG6AFG ON MCHTI.ADM_PROCESS
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007941.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_T0HQW87YGEIC61M5V6JWTM93A ON MCHTI.ADM_PARAM
(PARAM_NAME)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007936.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007742.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UKF3BCE3M572OWVUWFTS8M8L84P ON MCHTI.ZX_LOOKUP
(ZX_LOOKUP_KEYWORD, TITLE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.UK_O8WGM2698WNWTEOPRT7WXL37A ON MCHTI.ZX_LOOKUP
(CODE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.UK_38UXO2V0C36HNJ21W1EUMBNDI ON MCHTI.ZX_DESG
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007975.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK_P1WYHVUIHY0GK4FTW3I9KHDO9 ON MCHTI.ZX_DEPT
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007971.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UK9NW0DG8JNYMHXV8UKHN2890CQ ON MCHTI.ZX_ANY_OBJECT
(TITLE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.UK_D99A0WTG2VBMHU3HHHN7N3295 ON MCHTI.ZX_ANY_OBJECT
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007739.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C008023.
--  The object is created when the parent object is created.

CREATE TABLE MCHTI.ASSIGNMENT_HR
(
  ID              NUMBER(19,2)                  NOT NULL,
  CODE            VARCHAR2(20 CHAR)             NOT NULL,
  EMP_GROUP       VARCHAR2(20 CHAR),
  END_DATE        DATE,
  START_DATE      DATE                          NOT NULL,
  VERSION         NUMBER(10),
  DEPARTMENT_ID   NUMBER(19,2),
  DESIGNATION_ID  NUMBER(19,2),
  EMPLOYEE_ID     NUMBER(19,2)                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ASSIGNMENT_PRL
(
  ID               NUMBER(19,2)                 NOT NULL,
  BASIC            FLOAT(126),
  CODE             VARCHAR2(20 CHAR)            NOT NULL,
  CONVANCE         FLOAT(126),
  END_DATE         DATE,
  GROSS            FLOAT(126),
  HOUSE_RENT       FLOAT(126),
  MEDICAL          FLOAT(126),
  OTHER_ALLOWANCE  FLOAT(126),
  START_DATE       DATE,
  VERSION          NUMBER(10),
  EMPLOYEE_ID      NUMBER(19,2)                 NOT NULL,
  CONV             FLOAT(126),
  HR               FLOAT(126),
  MED              FLOAT(126)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ASSIGNMENT_TL
(
  ID                     NUMBER(19,2)           NOT NULL,
  CODE                   VARCHAR2(20 CHAR)      NOT NULL,
  END_DATE               DATE,
  IS_OVERTIME            NUMBER(1),
  START_DATE             DATE                   NOT NULL,
  VERSION                NUMBER(10),
  EMPLOYEE_ID            NUMBER(19,2)           NOT NULL,
  ROSTER_ID              NUMBER(19,2),
  SHIFT_ID               NUMBER(19,2),
  WEEKEND_SHIFT_OFF_DAY  VARCHAR2(9 BYTE)       DEFAULT 'FRIDAY'              NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.PROC_OUT_ATTN_DT
(
  ATTN_DATE     DATE                            NOT NULL,
  DT_ATTN_TYPE  VARCHAR2(30 CHAR)               NOT NULL,
  IN_TIME       DATE,
  OT            FLOAT(126),
  OUT_TIME      DATE,
  REMARKS       VARCHAR2(500 CHAR),
  EMPLOYEE_ID   NUMBER(19,2)                    NOT NULL,
  SHIFT_ID      NUMBER(19,2)                    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.PROC_OUT_EMP
(
  CITY                   VARCHAR2(30 CHAR),
  LINE_ONE               VARCHAR2(50 CHAR),
  LINE_TWO               VARCHAR2(50 CHAR),
  STREET                 VARCHAR2(30 CHAR),
  ZIP                    VARCHAR2(10 CHAR),
  CODE                   VARCHAR2(20 CHAR)      NOT NULL,
  DOB                    DATE,
  DOJ                    DATE,
  EMAIL                  VARCHAR2(30 CHAR),
  EMP_GROUP              VARCHAR2(20 CHAR),
  FULL_NAME              VARCHAR2(100 CHAR)     NOT NULL,
  GENDER                 VARCHAR2(6 CHAR),
  IS_OVERTIME            NUMBER(1),
  PIC_FILE               VARCHAR2(255 CHAR),
  WEEKEND_SHIFT_OFF_DAY  VARCHAR2(9 CHAR),
  VERSION                NUMBER(10),
  DEPARTMENT_ID          NUMBER(19,2),
  DESIGNATION_ID         NUMBER(19,2),
  EMPLOYEE_ID            NUMBER(19,2),
  ROSTER_ID              NUMBER(19,2),
  SHIFT_ID               NUMBER(19,2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.PROC_OUT_ROSTER
(
  CALC_DATE    DATE                             NOT NULL,
  EMPLOYEE_ID  NUMBER(19,2)                     NOT NULL,
  PERIOD_ID    NUMBER(19,2)                     NOT NULL,
  ROSTER_ID    NUMBER(19,2)                     NOT NULL,
  SHIFT_ID     NUMBER(19,2)                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ZX_EMP
(
  ID                        NUMBER(19,2)        NOT NULL,
  CODE                      VARCHAR2(20 CHAR)   NOT NULL,
  DOB                       DATE,
  DOC_FILE                  VARCHAR2(255 CHAR),
  EMAIL                     VARCHAR2(30 CHAR),
  FULL_NAME                 VARCHAR2(100 CHAR)  NOT NULL,
  IS_ACTIVE                 NUMBER(1),
  PIC_FILE                  VARCHAR2(255 CHAR),
  PIN                       VARCHAR2(30 CHAR),
  REMARKS                   VARCHAR2(2000 CHAR),
  SAL                       NUMBER(10,2),
  START_DATE                DATE,
  TAX_PAID                  NUMBER(10,2),
  VERSION                   NUMBER(10),
  WEB_ADDRESS               VARCHAR2(20 CHAR),
  ZX_GENDER                 VARCHAR2(20 CHAR),
  ZX_LOOKUP_BLOOD_GROUP_ID  NUMBER(19,2),
  ZX_DEPT_ID                NUMBER(19,2),
  ZX_DESG_ID                NUMBER(19,2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MCHTI.ZX_EMP_EDU_DTL
(
  ID                        NUMBER(19,2)        NOT NULL,
  CERTIFICATE_FILE          VARCHAR2(255 CHAR),
  CODE                      VARCHAR2(20 CHAR)   NOT NULL,
  EXAM                      VARCHAR2(20 CHAR)   NOT NULL,
  DOB                       DATE,
  PIC_FILE                  VARCHAR2(255 CHAR),
  REMARKS                   VARCHAR2(500 CHAR),
  SL_NO                     NUMBER(10),
  VERSION                   NUMBER(10),
  ZX_EMP_ID                 NUMBER(19,2)        NOT NULL,
  ZX_EMP_WHO_CHECKED_BY_ID  NUMBER(19,2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index MCHTI.SYS_C007761.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.PROC_OUT_EMP_PK ON MCHTI.PROC_OUT_EMP
(EMPLOYEE_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.PROC_OUT_EMP_U02 ON MCHTI.PROC_OUT_EMP
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007757.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007747.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.ASSIGNMENT_TL_U01 ON MCHTI.ASSIGNMENT_TL
(CODE)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007645.
--  The object is created when the parent object is created.

--  There is no statement for index MCHTI.SYS_C007745.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.ASSIGNMENT_HR_U01 ON MCHTI.ASSIGNMENT_HR
(CODE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.UK63BUCFGMGJISAPU863ATX02PH ON MCHTI.ZX_EMP_EDU_DTL
(CODE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MCHTI.UKGHNYXF8CIOSKNHF9LQI7MVV8H ON MCHTI.ZX_EMP_EDU_DTL
(ZX_EMP_ID, EXAM)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007765.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX MCHTI.UKLL0JGYSM5D23ARKYLGX9HDUME ON MCHTI.ZX_EMP
(FULL_NAME)
LOGGING
NOPARALLEL;


--  There is no statement for index MCHTI.SYS_C007763.
--  The object is created when the parent object is created.

ALTER TABLE MCHTI.ADM_PARAM ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_T0HQW87YGEIC61M5V6JWTM93A
  UNIQUE (PARAM_NAME)
  USING INDEX MCHTI.UK_T0HQW87YGEIC61M5V6JWTM93A
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ADM_PROCESS ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_ER7CCFDE575KLECL9LSKG6AFG
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_ER7CCFDE575KLECL9LSKG6AFG
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ADM_PROCESS_DETAIL ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UKCGERTCYSXNCWEA6DPQNEDVPEA
  UNIQUE (ADM_PROCESS_ID, ADM_PARAM_ID, ADM_ZONE_TYPE)
  USING INDEX MCHTI.UKCGERTCYSXNCWEA6DPQNEDVPEA
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ADM_REPORT ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_12A5A4GXF9JCHJ7DLMNW9BQ3O
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_12A5A4GXF9JCHJ7DLMNW9BQ3O
  ENABLE VALIDATE,
  CONSTRAINT UK_PBMRPPRR68RUIABL2AWCK3VLB
  UNIQUE (FILE_NAME)
  USING INDEX MCHTI.UK_PBMRPPRR68RUIABL2AWCK3VLB
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ADM_REPORT_DETAIL ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UKNQJ85REHRPQ7KHVQL95UJHB19
  UNIQUE (ADM_REPORT_ID, ADM_PARAM_ID)
  USING INDEX MCHTI.UKNQJ85REHRPQ7KHVQL95UJHB19
  ENABLE VALIDATE);

ALTER TABLE MCHTI.AUTH_MENU ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_RWUG86W16X8XH21XS8JK22JGB
  UNIQUE (URL_PATH)
  USING INDEX MCHTI.UK_RWUG86W16X8XH21XS8JK22JGB
  ENABLE VALIDATE);

ALTER TABLE MCHTI.AUTH_QUESTION ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.AUTH_REQUEST_MAP ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.AUTH_ROLE ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_SL3AD8KJNF8EBO7BERRSU1HO
  UNIQUE (AUTHORITY)
  USING INDEX MCHTI.UK_SL3AD8KJNF8EBO7BERRSU1HO
  ENABLE VALIDATE);

ALTER TABLE MCHTI.AUTH_TOKEN ADD (
  PRIMARY KEY
  (SERIES)
  ENABLE VALIDATE,
  CONSTRAINT UK_CN1M62UD9S70X2DUN44QKOD2P
  UNIQUE (TOKEN)
  USING INDEX MCHTI.UK_CN1M62UD9S70X2DUN44QKOD2P
  ENABLE VALIDATE,
  CONSTRAINT UK_FU8V8E6E6POK9SFW2VAA0WQBX
  UNIQUE (USERNAME)
  USING INDEX MCHTI.UK_FU8V8E6E6POK9SFW2VAA0WQBX
  ENABLE VALIDATE);

ALTER TABLE MCHTI.AUTH_USER ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT AUTH_USER_U01
  UNIQUE (USERNAME)
  USING INDEX MCHTI.AUTH_USER_U01
  ENABLE VALIDATE);

ALTER TABLE MCHTI.AUTH_USER_AUTH_QUESTION ADD (
  PRIMARY KEY
  (AUTH_QUESTION_ID, AUTH_USER_ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.AUTH_USER_AUTH_ROLE ADD (
  PRIMARY KEY
  (AUTH_USER_ID, AUTH_ROLE_ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.CLIENT ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_RB1NWD8YAH66CM1JQN55F5DRG
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_RB1NWD8YAH66CM1JQN55F5DRG
  ENABLE VALIDATE);

ALTER TABLE MCHTI.CLIENT_COMPANY ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_4SR4K1U0SXXQQ1JMBHL8JBX1T
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_4SR4K1U0SXXQQ1JMBHL8JBX1T
  ENABLE VALIDATE);

ALTER TABLE MCHTI.COMPANY ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_NIHSPJAA28E7UCECVP68H4AMH
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_NIHSPJAA28E7UCECVP68H4AMH
  ENABLE VALIDATE);

ALTER TABLE MCHTI.CUSTOMIZED_HOLIDAY_APP ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_E7J4JO8JQWDXKAHR112WANQ40
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_E7J4JO8JQWDXKAHR112WANQ40
  ENABLE VALIDATE);

ALTER TABLE MCHTI.DEPARTMENT ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_RH6EQ4TT0PG176FYHR58S6UXL
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_RH6EQ4TT0PG176FYHR58S6UXL
  ENABLE VALIDATE);

ALTER TABLE MCHTI.DESIGNATION ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_IJV6ABSH47WCHE44QUAFC5VE7
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_IJV6ABSH47WCHE44QUAFC5VE7
  ENABLE VALIDATE);

ALTER TABLE MCHTI.EMPLOYEE ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_T7BM2WG7CURAQJ764MM8ORUG8
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_T7BM2WG7CURAQJ764MM8ORUG8
  ENABLE VALIDATE);

ALTER TABLE MCHTI.GENERAL_HOLIDAY ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_72HK7RAQTDNIPYOKI9UXJNFD5
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_72HK7RAQTDNIPYOKI9UXJNFD5
  ENABLE VALIDATE);

ALTER TABLE MCHTI.HIBERNATE_SEQUENCES ADD (
  PRIMARY KEY
  (SEQUENCE_NAME)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.LEAVE_APP ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.LOOKUP ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UKOXOGAD86STS9G9SRTXXTK1PNK
  UNIQUE (KEYWORD, TITLE)
  USING INDEX MCHTI.UKOXOGAD86STS9G9SRTXXTK1PNK
  ENABLE VALIDATE);

ALTER TABLE MCHTI.MANUAL_ATTN_DAILY ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UKS4EH3QILLPF7CORNN721I63V3
  UNIQUE (EMPLOYEE_ID, ATTN_DATE)
  USING INDEX MCHTI.UKS4EH3QILLPF7CORNN721I63V3
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PERIOD ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PERSISTENT_LOGINS ADD (
  PRIMARY KEY
  (SERIES)
  ENABLE VALIDATE,
  CONSTRAINT UK_3GQ9WKITBP2AVE684IU50MHN7
  UNIQUE (TOKEN)
  USING INDEX MCHTI.UK_3GQ9WKITBP2AVE684IU50MHN7
  ENABLE VALIDATE,
  CONSTRAINT UK_A6C251UOVNX2CP2C3VV2DENTK
  UNIQUE (USERNAME)
  USING INDEX MCHTI.UK_A6C251UOVNX2CP2C3VV2DENTK
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PROC_OUT_ATTN_DAILY ADD (
  CONSTRAINT PROC_OUT_ATTN_DAILY_PK
  PRIMARY KEY
  (EMPLOYEE_ID, TRANSACTION_TIME)
  USING INDEX MCHTI.PROC_OUT_ATTN_DAILY_PK
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PROC_OUT_ATTN_PERIOD ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PROC_OUT_CALENDER ADD (
  CONSTRAINT PROC_OUT_CALENDER_PK
  PRIMARY KEY
  (CAL_DATE)
  USING INDEX MCHTI.PROC_OUT_CALENDER_PK
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ROSTER ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_N57PIT3MF92OK6IXIG8CIS7AW
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_N57PIT3MF92OK6IXIG8CIS7AW
  ENABLE VALIDATE);

ALTER TABLE MCHTI.SHIFT ADD (
  CHECK (END_BUF_MIN<=60 AND END_BUF_MIN>=0)
  ENABLE VALIDATE,
  CHECK (END_HR>=0 AND END_HR<=23)
  ENABLE VALIDATE,
  CHECK (END_MIN<=59 AND END_MIN>=0)
  ENABLE VALIDATE,
  CHECK (ORIENTATION_MIN<=60 AND ORIENTATION_MIN>=0)
  ENABLE VALIDATE,
  CHECK (START_BUF_MIN<=60 AND START_BUF_MIN>=0)
  ENABLE VALIDATE,
  CHECK (START_HR>=0 AND START_HR<=23)
  ENABLE VALIDATE,
  CHECK (START_MIN<=59 AND START_MIN>=0)
  ENABLE VALIDATE,
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_QTHLGMLLTHWG18UIYQBS0KXWR
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_QTHLGMLLTHWG18UIYQBS0KXWR
  ENABLE VALIDATE);

ALTER TABLE MCHTI.SUPPLIER ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_L66VGY7V2SNPH53MAF8ERN37
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_L66VGY7V2SNPH53MAF8ERN37
  ENABLE VALIDATE);

ALTER TABLE MCHTI.SUPPLIER_COMPANY ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_CMNA8LOP8AFHFSI0V0IJSU8SH
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_CMNA8LOP8AFHFSI0V0IJSU8SH
  ENABLE VALIDATE);

ALTER TABLE MCHTI.TRANSACSION ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ZX_ANY_OBJECT ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK9NW0DG8JNYMHXV8UKHN2890CQ
  UNIQUE (TITLE)
  USING INDEX MCHTI.UK9NW0DG8JNYMHXV8UKHN2890CQ
  ENABLE VALIDATE,
  CONSTRAINT UK_D99A0WTG2VBMHU3HHHN7N3295
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_D99A0WTG2VBMHU3HHHN7N3295
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ZX_DEPT ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_P1WYHVUIHY0GK4FTW3I9KHDO9
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_P1WYHVUIHY0GK4FTW3I9KHDO9
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ZX_DESG ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_38UXO2V0C36HNJ21W1EUMBNDI
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_38UXO2V0C36HNJ21W1EUMBNDI
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ZX_LOOKUP ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UKF3BCE3M572OWVUWFTS8M8L84P
  UNIQUE (ZX_LOOKUP_KEYWORD, TITLE)
  USING INDEX MCHTI.UKF3BCE3M572OWVUWFTS8M8L84P
  ENABLE VALIDATE,
  CONSTRAINT UK_O8WGM2698WNWTEOPRT7WXL37A
  UNIQUE (CODE)
  USING INDEX MCHTI.UK_O8WGM2698WNWTEOPRT7WXL37A
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ASSIGNMENT_HR ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT ASSIGNMENT_HR_U01
  UNIQUE (CODE)
  USING INDEX MCHTI.ASSIGNMENT_HR_U01
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ASSIGNMENT_PRL ADD (
  CHECK (basic>=1 AND basic<=100000)
  ENABLE VALIDATE,
  CHECK (convance>=1 AND convance<=100000)
  ENABLE VALIDATE,
  CHECK (gross>=1 AND gross<=100000)
  ENABLE VALIDATE,
  CHECK (HOUSE_RENT>=1 AND HOUSE_RENT<=100000)
  ENABLE VALIDATE,
  CHECK (medical>=1 AND medical<=100000)
  ENABLE VALIDATE,
  CHECK (OTHER_ALLOWANCE>=1 AND OTHER_ALLOWANCE<=100000)
  ENABLE VALIDATE,
  CHECK (conv>=1 AND conv<=100000)
  ENABLE VALIDATE,
  CHECK (hr>=1 AND hr<=100000)
  ENABLE VALIDATE,
  CHECK (med>=1 AND med<=100000)
  ENABLE VALIDATE,
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ASSIGNMENT_TL ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT ASSIGNMENT_TL_U01
  UNIQUE (CODE)
  USING INDEX MCHTI.ASSIGNMENT_TL_U01
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PROC_OUT_ATTN_DT ADD (
  PRIMARY KEY
  (ATTN_DATE, EMPLOYEE_ID)
  ENABLE VALIDATE,
  CONSTRAINT EMP_ATTN_DATE_UQ
  UNIQUE (EMPLOYEE_ID, ATTN_DATE)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PROC_OUT_EMP ADD (
  CONSTRAINT PROC_OUT_EMP_PK
  PRIMARY KEY
  (EMPLOYEE_ID)
  USING INDEX MCHTI.PROC_OUT_EMP_PK
  ENABLE VALIDATE,
  CONSTRAINT PROC_OUT_EMP_U02
  UNIQUE (CODE)
  USING INDEX MCHTI.PROC_OUT_EMP_U02
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PROC_OUT_ROSTER ADD (
  PRIMARY KEY
  (CALC_DATE, EMPLOYEE_ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ZX_EMP ADD (
  CHECK (sal>=1 AND sal<=100000)
  ENABLE VALIDATE,
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UKLL0JGYSM5D23ARKYLGX9HDUME
  UNIQUE (FULL_NAME)
  USING INDEX MCHTI.UKLL0JGYSM5D23ARKYLGX9HDUME
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ZX_EMP_EDU_DTL ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK63BUCFGMGJISAPU863ATX02PH
  UNIQUE (CODE)
  USING INDEX MCHTI.UK63BUCFGMGJISAPU863ATX02PH
  ENABLE VALIDATE,
  CONSTRAINT UKGHNYXF8CIOSKNHF9LQI7MVV8H
  UNIQUE (ZX_EMP_ID, EXAM)
  USING INDEX MCHTI.UKGHNYXF8CIOSKNHF9LQI7MVV8H
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ADM_PROCESS_DETAIL ADD (
  CONSTRAINT FKGFWMFJH2BPYYSADCY66GSQUS7 
  FOREIGN KEY (ADM_PROCESS_ID) 
  REFERENCES MCHTI.ADM_PROCESS (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKO1V0P9IG4015W3QXLEIAM98MW 
  FOREIGN KEY (ADM_PARAM_ID) 
  REFERENCES MCHTI.ADM_PARAM (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ADM_REPORT_DETAIL ADD (
  CONSTRAINT FK30J23FVPWR6AX300GV4CYG41G 
  FOREIGN KEY (ADM_PARAM_ID) 
  REFERENCES MCHTI.ADM_PARAM (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKGMS10R1UX44L3QYS7N5KCWY6D 
  FOREIGN KEY (ADM_REPORT_ID) 
  REFERENCES MCHTI.ADM_REPORT (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.AUTH_MENU ADD (
  CONSTRAINT FKEQQ7M46975BNUPAUAOECJVGSL 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES MCHTI.AUTH_MENU (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.AUTH_USER_AUTH_QUESTION ADD (
  CONSTRAINT FK80QJD7I37TWKXJ47FIU9LWC4O 
  FOREIGN KEY (AUTH_USER_ID) 
  REFERENCES MCHTI.AUTH_USER (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKJ3J0AAWAVP1F3NW5MSDGCD81W 
  FOREIGN KEY (AUTH_QUESTION_ID) 
  REFERENCES MCHTI.AUTH_QUESTION (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.AUTH_USER_AUTH_ROLE ADD (
  CONSTRAINT FK75ISXWSM0F5CIVP66QQBLS3OF 
  FOREIGN KEY (AUTH_ROLE_ID) 
  REFERENCES MCHTI.AUTH_ROLE (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKPN3SHKAKF8VMWYWEYXAVXP70X 
  FOREIGN KEY (AUTH_USER_ID) 
  REFERENCES MCHTI.AUTH_USER (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.LEAVE_APP ADD (
  CONSTRAINT FKFI52BRVTXBTNM252AY5UUSWTM 
  FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES MCHTI.EMPLOYEE (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.MANUAL_ATTN_DAILY ADD (
  CONSTRAINT FKG63N9U2U2NNED8UVBQ66OUHEM 
  FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES MCHTI.EMPLOYEE (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_9M2RT37ETAOC35S5RH8D10JC7 
  FOREIGN KEY (ENTRY_BY_ID) 
  REFERENCES MCHTI.AUTH_USER (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_KKNAOM0FMYWJ4U52LEOQV8K8G 
  FOREIGN KEY (EDIT_BY_ID) 
  REFERENCES MCHTI.AUTH_USER (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PROC_OUT_ATTN_DAILY ADD (
  CONSTRAINT FKC0KN69UE6I5VFX08O3NLN7VG5 
  FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES MCHTI.EMPLOYEE (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PROC_OUT_ATTN_PERIOD ADD (
  CONSTRAINT FK65VWNTY3KAAMILP0TCVPWS8LF 
  FOREIGN KEY (PERIOD_ID) 
  REFERENCES MCHTI.PERIOD (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKDA89181GHBX7BFBR80EH2FCI8 
  FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES MCHTI.EMPLOYEE (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ASSIGNMENT_HR ADD (
  CONSTRAINT FK7FN2LBRO5BA22S3FYLNKSMWSD 
  FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES MCHTI.EMPLOYEE (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK8ATJJ4O6A55TQ22Y7GHC1NPYP 
  FOREIGN KEY (DEPARTMENT_ID) 
  REFERENCES MCHTI.DEPARTMENT (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKKFN4NH1W1NR2TE7V0PUEOLC43 
  FOREIGN KEY (DESIGNATION_ID) 
  REFERENCES MCHTI.DESIGNATION (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ASSIGNMENT_PRL ADD (
  CONSTRAINT FKLH1V6I78LCOGKC6RRIUNX9K6P 
  FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES MCHTI.EMPLOYEE (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ASSIGNMENT_TL ADD (
  CONSTRAINT FK5867VS8Y4U12D83RLN3NPKHX6 
  FOREIGN KEY (SHIFT_ID) 
  REFERENCES MCHTI.SHIFT (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK7166OUQT27FFJQ7HG9BFNXDSO 
  FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES MCHTI.EMPLOYEE (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKOGUT91O23M7E7L95PING6BLYE 
  FOREIGN KEY (ROSTER_ID) 
  REFERENCES MCHTI.ROSTER (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PROC_OUT_ATTN_DT ADD (
  CONSTRAINT FK16J8DU2GQRM81VY45IFW3UJTV 
  FOREIGN KEY (SHIFT_ID) 
  REFERENCES MCHTI.SHIFT (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK4QJMUUAL40R7MJQSHCP57S2DI 
  FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES MCHTI.EMPLOYEE (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PROC_OUT_EMP ADD (
  CONSTRAINT FK2CP5S36QW2U5YHB4KAE4BMMK3 
  FOREIGN KEY (SHIFT_ID) 
  REFERENCES MCHTI.SHIFT (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK2KPF2GKUNXHFUUQLRBDH92G28 
  FOREIGN KEY (DESIGNATION_ID) 
  REFERENCES MCHTI.DESIGNATION (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK7LYOF5QFGCLDIPHN4QOR3QGOO 
  FOREIGN KEY (DEPARTMENT_ID) 
  REFERENCES MCHTI.DEPARTMENT (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK9HU0A0EH3IHG856HT9M6M4GR8 
  FOREIGN KEY (ROSTER_ID) 
  REFERENCES MCHTI.ROSTER (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKCLUIYQ0P07EETJUHT2FQ87SCT 
  FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES MCHTI.EMPLOYEE (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.PROC_OUT_ROSTER ADD (
  CONSTRAINT FK27N859C8I0XU45WMM2D7E1LMS 
  FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES MCHTI.EMPLOYEE (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKAA80AATLSPFDT896A2TRFBAKO 
  FOREIGN KEY (SHIFT_ID) 
  REFERENCES MCHTI.SHIFT (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKAFX32LLTW64THG877CRC59TU4 
  FOREIGN KEY (PERIOD_ID) 
  REFERENCES MCHTI.PERIOD (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKCPJICQP0C2JOC81IHCPK52P4D 
  FOREIGN KEY (ROSTER_ID) 
  REFERENCES MCHTI.ROSTER (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ZX_EMP ADD (
  CONSTRAINT FK58PXRACJR7CUQLMOFTCDFM0SX 
  FOREIGN KEY (ZX_LOOKUP_BLOOD_GROUP_ID) 
  REFERENCES MCHTI.ZX_LOOKUP (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKM1HCPU1Q6UJCSUJDKFTRPDPNE 
  FOREIGN KEY (ZX_DESG_ID) 
  REFERENCES MCHTI.ZX_DESG (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKT33SRM43W0RV9SHXYS9CKQBGE 
  FOREIGN KEY (ZX_DEPT_ID) 
  REFERENCES MCHTI.ZX_DEPT (ID)
  ENABLE VALIDATE);

ALTER TABLE MCHTI.ZX_EMP_EDU_DTL ADD (
  CONSTRAINT FKEP4DJHHCMQGH6USXAHP45RKQJ 
  FOREIGN KEY (ZX_EMP_ID) 
  REFERENCES MCHTI.ZX_EMP (ID)
  ENABLE VALIDATE,
  CONSTRAINT FKFH2UEH65FE68G1EETJD8GWS24 
  FOREIGN KEY (ZX_EMP_WHO_CHECKED_BY_ID) 
  REFERENCES MCHTI.ZX_EMP (ID)
  ENABLE VALIDATE);
