SET DEFINE OFF;
Insert into PROC_OUT_ATTN_PERIOD
   (ID, ATTN_STS, DAY_ABSENT, DAY_PRESENT, GEN_TYPE, 
    OT_HOUR_HOLIDAY, EMPLOYEE_ID, PERIOD_ID)
 Values
   (44117, 0, 2, 22, 1, 
    2, 1, 1);
COMMIT;
