SET DEFINE OFF;
Insert into MCHTI.AUTH_USER_AUTH_ROLE
   (AUTH_USER_ID, AUTH_ROLE_ID)
 Values
   (1, 43405);
Insert into MCHTI.AUTH_USER_AUTH_ROLE
   (AUTH_USER_ID, AUTH_ROLE_ID)
 Values
   (2, 43405);
Insert into MCHTI.AUTH_USER_AUTH_ROLE
   (AUTH_USER_ID, AUTH_ROLE_ID)
 Values
   (43406, 43405);
Insert into MCHTI.AUTH_USER_AUTH_ROLE
   (AUTH_USER_ID, AUTH_ROLE_ID)
 Values
   (43407, 43405);
Insert into MCHTI.AUTH_USER_AUTH_ROLE
   (AUTH_USER_ID, AUTH_ROLE_ID)
 Values
   (43408, 43405);
COMMIT;
